# Generated by Django 3.2.16 on 2022-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
