version: "3"

services:
  redis:
    image: redis:7.0
    container_name: instashare_redis
    networks:
      instashare_subnet:
        aliases:
          - redis
  db:
    image: postgres:13.4
    restart: always
    container_name: instashare_db
    networks:
      instashare_subnet:
        aliases:
          - db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    container_name: instashare_api
    build: .
    volumes:
      - static_files:/code/instashare_api/static/
      - media_files:/code/instashare_api/media/
      - ./data/logs:/code/logs/
    env_file:
      - .env
    networks:
      instashare_subnet:
        aliases:
          - api
    depends_on:
      - db
    restart: always
  nginx:
    image: nginx:1.23.2
    container_name: instashare_nginx
    ports:
      - "8003:80"
    volumes:
      - static_files:/code/instashare_api/static
      - media_files:/code/instashare_api/media
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      instashare_subnet:
        aliases:
          - nginx
    restart: "on-failure"
  worker:
    container_name: instashare_worker
    build: .
    command: celery -A config worker -l INFO
    env_file:
      - .env
    networks:
      instashare_subnet:
        aliases:
          - worker
    depends_on:
      - db
      - redis

networks:
  instashare_subnet:

volumes:
  static_files:
  media_files:
